### PR TITLE
[e2istream] Add cmdwrapper

### PR DESCRIPTION
**Pull request by fairbird**

### CODE REVIEW

**Comment by Hains** [comment]
Do we really need e2istream?  
It's just a old and unmaintained version of e2iplayer.
Can you tell me what e2istream does and e2iplayer not?

Besided it doesn't build.
You need to change the name of the root directory.
IPTVPLAYER => e.g  E2ISTREAM.

Because e2iplayer has IPTVPLAYER as root directory as well.

**Comment by fairbird** [comment]
The important things (E2ISTREAM) the Owen of source support new openssl 1.1 ..
And he have server of updating and plugin always updated those stopped hosts site ...

(IPTVPLAYER) we have our source right .. But we know we don't have update server and all servers update doesn't support openssl 1.1 (If we plugin then stop working and tell it no supported to openssl 1.1)

No need to add e2istream and e2iplayer in feed recipes just one plugin other one just If we want to build it can be build it separate.

**Comment by Hains** [comment]
A)
E2istream is built from our sources, with openssl 1.1..x support.
https://github.com/persianpros/e2istream/commits/master
When you update e2istream from external server, you still have openssl 1.1.x support?

B)
Yes that's akward, we need figure ou solution for that.
Like Persian Prince said, we can create tarball from our sources, so users can update online without buid server.

C)
If you change the root directory name of e2istream player, you can build both plugins at the same time.
Changing plugin name in feed recipe is not done.

**Comment by fairbird** [comment]
Yes of course as I wrote before on our forum and here also ...
Update default external server works and after updated still have openssl 1.1.x support
Even if I download and install the plugin from official silt 

> wget http://www.softrix.co.uk/istream/installer.sh -O - | /bin/sh

and here is site of the Owner mod and support plugin
http://www.softrix.co.uk/istream/

**Comment by Hains** [comment]
So recipe for e2istream is pointless since you can install the plugin from website  and update from there.

**Comment by Hains** [comment]
To be honest i'm getting a little bit tired of these plugins.
You can help us with update e2iplayer, like @kueken  does.
@persianpros and i spend a lot of time to make the plugin better as well.
For users without feed server you can post IPK file of e2iplayer, so users can upload IPK file to /tmp dir and install plugin manually.
OK, not so easy as an online update, but it can be done easily.

I'll remove e2istream recipe and keep e2iplayer only.
If you need it, you can add it to your own build-env.

These plugins are a waste of time and only useful to update our own e2iplayer (add/remove host etc).

**Pull request closed without merging**
